"""Verify release archives without extracting or executing their contents."""

from __future__ import annotations

import argparse
import tarfile
import zipfile
from collections.abc import Iterable
from email import policy
from email.parser import BytesParser
from pathlib import Path, PurePosixPath


class DistributionError(RuntimeError):
    """A built distribution is missing required content or contains private files."""


_FORBIDDEN_PARTS = {
    ".docdex",
    ".docdex-state",
    ".jevcompiler",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    "keys.env",
    "private",
    "secrets",
    "spec.md",
}


def _archive_names(names: Iterable[str], *, archive: str) -> set[str]:
    checked: set[str] = set()
    for name in names:
        path = PurePosixPath(name)
        if path.is_absolute() or ".." in path.parts:
            raise DistributionError(f"{archive} contains an unsafe path: {name}")
        parts = tuple(part.casefold() for part in path.parts)
        forbidden = _FORBIDDEN_PARTS.intersection(parts)
        if forbidden or any(part == ".env" or part.endswith(".env") for part in parts):
            raise DistributionError(f"{archive} contains a private path: {name}")
        if parts and parts[-1].endswith((".pyc", ".pyo")):
            raise DistributionError(f"{archive} contains generated bytecode: {name}")
        checked.add(name)
    return checked


def _only(directory: Path, pattern: str, *, label: str) -> Path:
    matches = sorted(directory.glob(pattern))
    if len(matches) != 1:
        raise DistributionError(
            f"expected exactly one {label} in {directory}, found {len(matches)}"
        )
    return matches[0]


def _require(names: set[str], required: set[str], *, archive: str) -> None:
    missing = sorted(required - names)
    if missing:
        raise DistributionError(f"{archive} is missing required files: {missing}")


def _verify_wheel(path: Path) -> int:
    with zipfile.ZipFile(path) as wheel:
        names = _archive_names(wheel.namelist(), archive="wheel")
        _require(
            names,
            {"jevcompiler/py.typed", "jevcompiler/freeze/runtime.ts"},
            archive="wheel",
        )
        metadata_paths = sorted(
            name for name in names if name.endswith(".dist-info/METADATA")
        )
        if len(metadata_paths) != 1:
            raise DistributionError(
                f"wheel must contain one METADATA file, found {len(metadata_paths)}"
            )
        metadata_path = metadata_paths[0]
        dist_info = metadata_path.rsplit("/", 1)[0]
        entry_points_path = f"{dist_info}/entry_points.txt"
        _require(names, {entry_points_path}, archive="wheel")

        metadata = BytesParser(policy=policy.default).parsebytes(wheel.read(metadata_path))
        if metadata.get("Name") != "jevcompiler":
            raise DistributionError("wheel metadata Name must be 'jevcompiler'")
        if not metadata.get("Version"):
            raise DistributionError("wheel metadata must declare a Version")
        if metadata.get("Requires-Python") != ">=3.11":
            raise DistributionError("wheel metadata Requires-Python must be '>=3.11'")

        entry_points = wheel.read(entry_points_path).decode("utf-8").splitlines()
        if "jevcompiler = jevcompiler.cli:app" not in (line.strip() for line in entry_points):
            raise DistributionError("wheel is missing the jevcompiler console entry point")
        return len(names)


def _verify_sdist(path: Path) -> int:
    with tarfile.open(path, mode="r:gz") as sdist:
        names = _archive_names(sdist.getnames(), archive="sdist")
    roots = {PurePosixPath(name).parts[0] for name in names if PurePosixPath(name).parts}
    if len(roots) != 1:
        raise DistributionError(f"sdist must have one root directory, found {sorted(roots)}")
    root = roots.pop()
    _require(
        names,
        {
            f"{root}/LICENSE",
            f"{root}/README.md",
            f"{root}/pyproject.toml",
            f"{root}/src/jevcompiler/freeze/runtime.ts",
            f"{root}/src/jevcompiler/py.typed",
        },
        archive="sdist",
    )
    return len(names)


def verify_distributions(directory: Path) -> tuple[Path, int, Path, int]:
    if not directory.is_dir():
        raise DistributionError(f"distribution directory does not exist: {directory}")
    wheel = _only(directory, "*.whl", label="wheel")
    sdist = _only(directory, "*.tar.gz", label="source distribution")
    return wheel, _verify_wheel(wheel), sdist, _verify_sdist(sdist)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directory", type=Path, help="Directory containing one wheel and one sdist")
    args = parser.parse_args()
    try:
        wheel, wheel_count, sdist, sdist_count = verify_distributions(args.directory)
    except (DistributionError, OSError, tarfile.TarError, zipfile.BadZipFile) as exc:
        raise SystemExit(f"distribution verification failed: {exc}") from None
    print(
        f"Verified {wheel.name} ({wheel_count} files) and "
        f"{sdist.name} ({sdist_count} files)."
    )


if __name__ == "__main__":
    main()
